name: Deploy Fullstack App (Frontend + Backend)

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  FRONTEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/react-app
  BACKEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app

  EC2_HOST: ${{ secrets.HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_KEY: ${{ secrets.KEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      # === Build & Push Frontend ===
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest

      # === Build & Push Backend ===
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

      # === Deploy to EC2 ===
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_KEY }}
          port: ${{ env.PORT }}
          script: |
            echo "==== Pull latest Docker images ===="
            docker pull ${{ env.FRONTEND_IMAGE }}:latest
            docker pull ${{ env.BACKEND_IMAGE }}:latest

            echo "==== Stop & Remove old containers ===="
            docker stop frontend || true
            docker rm frontend || true
            docker stop backend || true
            docker rm backend || true

            echo "==== Run new containers ===="
            docker run -d --restart always --name frontend -p 80:80 ${{ env.FRONTEND_IMAGE }}:latest
            docker run -d --restart always --name backend -p 3000:3000 ${{ env.BACKEND_IMAGE }}:latest

            echo "==== Cleanup old images ===="
            docker image prune -f
